/* =============================================================================
 * EMG-Based Biometric Bootloader — STM32F401RE
 * FreeRTOS | ADC | UART | Green LED (boot) → OTA → Red LED (app)
 *
 * Flash layout:
 *   Bootloader  : 0x08000000  (Sector 0, 16 KB)
 *   Application : 0x08008000  (Sector 2 onwards)
 *
 * Wiring (Nucleo-F401RE):
 *   EMG sensor OUT → PA0  (ADC1_IN0)
 *   Green LED      → PA5  (LD2, on-board)
 *   Red   LED      → PB0  (external, 330 Ω to GND)
 *   UART2 TX       → PA2  (ST-Link virtual COM)
 *   UART2 RX       → PA3
 *
 * Build: STM32CubeIDE  |  HAL + FreeRTOS (CMSIS-OS v1) middleware enabled
 * =============================================================================*/

#include "main.h"
#include "cmsis_os.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

/* ── HAL handles (generated by CubeMX) ─────────────────────────────────────*/
ADC_HandleTypeDef  hadc1;
UART_HandleTypeDef huart2;

/* ── FreeRTOS task handles ──────────────────────────────────────────────────*/
osThreadId emgTaskHandle;
osThreadId appTaskHandle;

/* ── Config ─────────────────────────────────────────────────────────────────*/
#define APP_START_ADDR       0x08008000UL   /* application vector table      */
#define ADC_SAMPLES          16             /* moving-average window          */
#define EMG_THRESHOLD        1800           /* 12-bit ADC counts (~1.4 V)    */
#define EMG_HOLD_COUNT       5              /* consecutive hits to confirm    */
#define GREEN_LED_PIN        GPIO_PIN_5
#define GREEN_LED_PORT       GPIOA
#define RED_LED_PIN          GPIO_PIN_0
#define RED_LED_PORT         GPIOB
#define UART_TIMEOUT_MS      10

/* ── Helpers ─────────────────────────────────────────────────────────────────*/
static void uart_print(const char *fmt, ...)
{
    char buf[128];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    HAL_UART_Transmit(&huart2, (uint8_t *)buf, strlen(buf), UART_TIMEOUT_MS);
}

/* ── Moving-average ADC read ─────────────────────────────────────────────────*/
static uint32_t emg_read_averaged(void)
{
    uint32_t sum = 0;
    for (uint8_t i = 0; i < ADC_SAMPLES; i++) {
        HAL_ADC_Start(&hadc1);
        HAL_ADC_PollForConversion(&hadc1, 10);
        sum += HAL_ADC_GetValue(&hadc1);
        HAL_ADC_Stop(&hadc1);
        osDelay(2);
    }
    return sum / ADC_SAMPLES;
}

/* ── Jump to application ─────────────────────────────────────────────────────
 *  1. Disable interrupts
 *  2. Set MSP from first word of application vector table
 *  3. Jump to Reset_Handler (second word)
 * --------------------------------------------------------------------------*/
static void jump_to_application(void)
{
    typedef void (*pFunction)(void);

    /* Sanity-check: is there a valid stack pointer at APP_START_ADDR? */
    uint32_t app_sp = *(volatile uint32_t *)APP_START_ADDR;
    if ((app_sp & 0xFF000000) != 0x20000000) {
        uart_print("[BOOT] No valid application found at 0x%08X\r\n", APP_START_ADDR);
        return;
    }

    uart_print("[BOOT] Jumping to application at 0x%08X\r\n", APP_START_ADDR);
    HAL_Delay(50);                      /* flush UART                        */

    __disable_irq();

    /* Remap vector table */
    SCB->VTOR = APP_START_ADDR;

    /* Set stack pointer */
    __set_MSP(app_sp);

    /* Call application Reset_Handler */
    pFunction app_reset = (pFunction)(*(volatile uint32_t *)(APP_START_ADDR + 4));
    app_reset();

    /* Should never reach here */
    while (1) {}
}

/* ── Task 1: EMG Acquisition & Bootloader Decision ──────────────────────────*/
void emgTask(void const *argument)
{
    uint8_t  confirm_count = 0;
    uint32_t emg_val;

    /* Signal boot-ready: green LED ON */
    HAL_GPIO_WritePin(GREEN_LED_PORT, GREEN_LED_PIN, GPIO_PIN_SET);
    uart_print("\r\n[BOOT] EMG Bootloader ready — muscle contraction to trigger OTA\r\n");
    uart_print("[BOOT] Threshold: %d ADC counts | Window: %d samples\r\n",
               EMG_THRESHOLD, ADC_SAMPLES);

    for (;;) {
        emg_val = emg_read_averaged();
        uart_print("[EMG]  ADC avg = %4lu\r\n", emg_val);

        if (emg_val > EMG_THRESHOLD) {
            confirm_count++;
            uart_print("[EMG]  Above threshold (%u/%u)\r\n", confirm_count, EMG_HOLD_COUNT);

            if (confirm_count >= EMG_HOLD_COUNT) {
                /* ── OTA TRIGGER ─────────────────────────────────────────── */
                uart_print("[BOOT] EMG confirmed — OTA handover initiated\r\n");

                /* Green OFF while updating */
                HAL_GPIO_WritePin(GREEN_LED_PORT, GREEN_LED_PIN, GPIO_PIN_RESET);

                /* In a real system: receive new binary over UART/CAN/BLE here
                 * and write it to flash using HAL_FLASH_Program().
                 * For this demo we assume the application is already flashed. */
                uart_print("[OTA]  Simulating firmware write... done\r\n");
                HAL_Delay(500);

                /* Signal success and jump */
                uart_print("[OTA]  OTA_UPDATE_DONE\r\n");   /* Python listens for this */
                HAL_Delay(100);

                jump_to_application();

                /* If no app found, restart bootloader */
                confirm_count = 0;
                HAL_GPIO_WritePin(GREEN_LED_PORT, GREEN_LED_PIN, GPIO_PIN_SET);
            }
        } else {
            if (confirm_count > 0) {
                uart_print("[EMG]  Signal lost, resetting counter\r\n");
            }
            confirm_count = 0;
        }

        osDelay(100);   /* 10 Hz polling rate                                */
    }
}

/* ── Task 2: Application LED (runs only AFTER vector-table jump) ─────────────
 *  This task lives in the APPLICATION binary (0x08008000).
 *  It is provided here for reference — copy it into your application project.
 * --------------------------------------------------------------------------*/
void appRedLedTask(void const *argument)
{
    /* Confirm OTA success: red LED blinks */
    uart_print("[APP]  Application started after OTA handover\r\n");

    for (;;) {
        HAL_GPIO_TogglePin(RED_LED_PORT, RED_LED_PIN);
        uart_print("[APP]  Running — red LED toggle\r\n");
        osDelay(500);
    }
}

/* ── main ─────────────────────────────────────────────────────────────────── */
int main(void)
{
    HAL_Init();
    SystemClock_Config();   /* generated by CubeMX */
    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_USART2_UART_Init();

    /* Create EMG acquisition task (bootloader side) */
    osThreadDef(emgTask, emgTask, osPriorityNormal, 0, 256);
    emgTaskHandle = osThreadCreate(osThread(emgTask), NULL);

    /* Start scheduler */
    osKernelStart();

    /* Should never reach here */
    while (1) {}
}

/* ── Minimal CubeMX-generated stubs (fill from your .ioc generated code) ────*/

void SystemClock_Config(void)
{
    /* 84 MHz via HSI + PLL — configure in CubeMX and paste generated code here */
}

void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* Green LED — PA5 */
    GPIO_InitStruct.Pin   = GREEN_LED_PIN;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GREEN_LED_PORT, &GPIO_InitStruct);

    /* Red LED — PB0 */
    GPIO_InitStruct.Pin = RED_LED_PIN;
    HAL_GPIO_Init(RED_LED_PORT, &GPIO_InitStruct);

    /* EMG ADC pin — PA0 (configured as analog by MX_ADC1_Init) */
}

void MX_ADC1_Init(void)
{
    ADC_ChannelConfTypeDef sConfig = {0};
    __HAL_RCC_ADC1_CLK_ENABLE();

    hadc1.Instance                   = ADC1;
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = DISABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = 1;
    HAL_ADC_Init(&hadc1);

    sConfig.Channel      = ADC_CHANNEL_0;   /* PA0 */
    sConfig.Rank         = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_480CYCLES;
    HAL_ADC_ConfigChannel(&hadc1, &sConfig);
}

void MX_USART2_UART_Init(void)
{
    __HAL_RCC_USART2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};
    GPIO_InitStruct.Pin       = GPIO_PIN_2 | GPIO_PIN_3;   /* TX, RX */
    GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull      = GPIO_NOPULL;
    GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF7_USART2;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    HAL_UART_Init(&huart2);
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}
